export type Direction = "Bắc" | "Nam" | "Đông" | "Tây" | "Đông Bắc" | "Đông Nam" | "Tây Bắc" | "Tây Nam"

export type PostDraftStatus = "draft" | "pending" | "published" | "rejected" | "expired"

export interface DraftPost {
  draft_id: number
  user_id: number
  title: string
  slug: string
  address: string
  price: number
  square_meters: number
  description: string
  floor: number
  bedroom: number
  bathroom: number
  isFurniture: boolean
  direction: Direction
  expiredDate: string
  priority: number
  status: PostDraftStatus
  created_at: string
  updated_at: string
  image?: string // Optional field for property image
}

export interface User {
  user_id: number
  name: string
  avatar?: string
}

// Mock users
export const mockUsers: User[] = [
    {
      user_id: 1,
      name: "Nguyễn Văn A",
      avatar: "https://images.hdqwalls.com/wallpapers/gwen-stacy-among-the-skyscrapers-hi.jpg",
    },
    {
      user_id: 2,
      name: "Trần Thị B",
      avatar: "https://images.hdqwalls.com/wallpapers/gwen-stacy-among-the-skyscrapers-hi.jpg",
    },
    {
      user_id: 3,
      name: "Lê Văn C",
      avatar: "https://images.hdqwalls.com/wallpapers/gwen-stacy-among-the-skyscrapers-hi.jpg",
    },
  ]
  
  // Mock draft posts
  export const mockDraftPosts: DraftPost[] = [
    {
      draft_id: 1,
      user_id: 1,
      title: "Căn hộ cao cấp Quận 1",
      slug: "can-ho-cao-cap-quan-1",
      address: "123 Nguyễn Trãi, Quận 1, TP. Hồ Chí Minh",
      price: 5000000000,
      square_meters: 100,
      description: "Căn hộ sang trọng, đầy đủ nội thất, vị trí trung tâm.",
      floor: 10,
      bedroom: 3,
      bathroom: 2,
      isFurniture: true,
      direction: "Bắc",
      expiredDate: "2023-12-31T23:59:59Z",
      priority: 1,
      status: "draft",
      created_at: "2023-10-15T10:00:00Z",
      updated_at: "2023-10-18T14:30:00Z",
      image: "https://images.hdqwalls.com/wallpapers/gwen-stacy-among-the-skyscrapers-hi.jpg",
    },
    {
      draft_id: 2,
      user_id: 1,
      title: "Nhà phố Thảo Điền",
      slug: "nha-pho-thao-dien",
      address: "45 Quốc Hương, Thảo Điền, Quận 2, TP. Hồ Chí Minh",
      price: 12000000000,
      square_meters: 200,
      description: "Nhà phố hiện đại, khu vực an ninh, gần trường quốc tế.",
      floor: 3,
      bedroom: 4,
      bathroom: 3,
      isFurniture: false,
      direction: "Nam",
      expiredDate: "2023-12-25T23:59:59Z",
      priority: 2,
      status: "draft",
      created_at: "2023-10-10T08:15:00Z",
      updated_at: "2023-10-17T11:45:00Z",
      image: "https://images.hdqwalls.com/wallpapers/gwen-stacy-among-the-skyscrapers-hi.jpg",
    },
    {
      draft_id: 3,
      user_id: 2,
      title: "Biệt thự Phú Mỹ Hưng",
      slug: "biet-thu-phu-my-hung",
      address: "78 Nguyễn Lương Bằng, Phú Mỹ Hưng, Quận 7, TP. Hồ Chí Minh",
      price: 25000000000,
      square_meters: 350,
      description: "Biệt thự sang trọng, sân vườn rộng, hồ bơi riêng.",
      floor: 2,
      bedroom: 5,
      bathroom: 4,
      isFurniture: true,
      direction: "Đông",
      expiredDate: "2023-12-20T23:59:59Z",
      priority: 3,
      status: "pending",
      created_at: "2023-10-05T15:20:00Z",
      updated_at: "2023-10-16T09:10:00Z",
      image: "https://images.hdqwalls.com/wallpapers/gwen-stacy-among-the-skyscrapers-hi.jpg",
    },
    {
      draft_id: 4,
      user_id: 2,
      title: "Căn hộ Vinhomes Central Park",
      slug: "can-ho-vinhomes-central-park",
      address: "208 Nguyễn Hữu Cảnh, Bình Thạnh, TP. Hồ Chí Minh",
      price: 7500000000,
      square_meters: 85,
      description: "Căn hộ view sông, nội thất cao cấp, tiện ích đầy đủ.",
      floor: 15,
      bedroom: 2,
      bathroom: 2,
      isFurniture: true,
      direction: "Tây",
      expiredDate: "2023-12-15T23:59:59Z",
      priority: 0,
      status: "draft",
      created_at: "2023-09-28T12:40:00Z",
      updated_at: "2023-10-15T16:25:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 5,
      user_id: 3,
      title: "Nhà mặt tiền Lê Văn Sỹ",
      slug: "nha-mat-tien-le-van-sy",
      address: "156 Lê Văn Sỹ, Quận 3, TP. Hồ Chí Minh",
      price: 18000000000,
      square_meters: 120,
      description: "Nhà mặt tiền kinh doanh, vị trí đắc địa, giao thông thuận lợi.",
      floor: 4,
      bedroom: 3,
      bathroom: 3,
      isFurniture: false,
      direction: "Đông Nam",
      expiredDate: "2023-12-10T23:59:59Z",
      priority: 1,
      status: "draft",
      created_at: "2023-09-20T09:30:00Z",
      updated_at: "2023-10-14T13:15:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 6,
      user_id: 3,
      title: "Căn hộ Masteri An Phú",
      slug: "can-ho-masteri-an-phu",
      address: "179 Xa lộ Hà Nội, An Phú, Quận 2, TP. Hồ Chí Minh",
      price: 4200000000,
      square_meters: 70,
      description: "Căn hộ 2 phòng ngủ, nội thất cơ bản, gần Metro.",
      floor: 8,
      bedroom: 2,
      bathroom: 1,
      isFurniture: true,
      direction: "Bắc",
      expiredDate: "2023-12-05T23:59:59Z",
      priority: 0,
      status: "rejected",
      created_at: "2023-09-18T14:20:00Z",
      updated_at: "2023-10-13T10:45:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 7,
      user_id: 1,
      title: "Shophouse Sala Đại Quang Minh",
      slug: "shophouse-sala-dai-quang-minh",
      address: "10 Mai Chí Thọ, Thủ Thiêm, Quận 2, TP. Hồ Chí Minh",
      price: 35000000000,
      square_meters: 180,
      description: "Shophouse vị trí đẹp, kinh doanh sầm uất, thiết kế hiện đại.",
      floor: 5,
      bedroom: 4,
      bathroom: 4,
      isFurniture: false,
      direction: "Nam",
      expiredDate: "2023-12-01T23:59:59Z",
      priority: 2,
      status: "draft",
      created_at: "2023-09-15T11:10:00Z",
      updated_at: "2023-10-12T15:30:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 8,
      user_id: 2,
      title: "Căn hộ Sunrise City",
      slug: "can-ho-sunrise-city",
      address: "23 Nguyễn Hữu Thọ, Quận 7, TP. Hồ Chí Minh",
      price: 6800000000,
      square_meters: 110,
      description: "Căn hộ 3 phòng ngủ, nội thất cao cấp, view thành phố.",
      floor: 12,
      bedroom: 3,
      bathroom: 2,
      isFurniture: true,
      direction: "Tây Nam",
      expiredDate: "2023-11-30T23:59:59Z",
      priority: 1,
      status: "draft",
      created_at: "2023-09-12T09:45:00Z",
      updated_at: "2023-10-11T14:20:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 9,
      user_id: 3,
      title: "Nhà phố Lakeview City",
      slug: "nha-pho-lakeview-city",
      address: "32 Song Hành, An Phú, Quận 2, TP. Hồ Chí Minh",
      price: 15000000000,
      square_meters: 160,
      description: "Nhà phố view hồ, thiết kế Singapore, an ninh 24/7.",
      floor: 3,
      bedroom: 4,
      bathroom: 3,
      isFurniture: false,
      direction: "Đông Bắc",
      expiredDate: "2023-11-25T23:59:59Z",
      priority: 0,
      status: "pending",
      created_at: "2023-09-10T13:30:00Z",
      updated_at: "2023-10-10T11:15:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 10,
      user_id: 1,
      title: "Căn hộ Estella Heights",
      slug: "can-ho-estella-heights",
      address: "88 Song Hành, An Phú, Quận 2, TP. Hồ Chí Minh",
      price: 8500000000,
      square_meters: 125,
      description: "Căn hộ cao cấp, thiết kế sang trọng, tiện ích 5 sao.",
      floor: 18,
      bedroom: 3,
      bathroom: 2,
      isFurniture: true,
      direction: "Đông",
      expiredDate: "2023-11-20T23:59:59Z",
      priority: 3,
      status: "draft",
      created_at: "2023-09-08T10:20:00Z",
      updated_at: "2023-10-09T16:40:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 11,
      user_id: 2,
      title: "Biệt thự Riviera Cove",
      slug: "biet-thu-riviera-cove",
      address: "45 Nguyễn Văn Tưởng, Quận 9, TP. Hồ Chí Minh",
      price: 28000000000,
      square_meters: 400,
      description: "Biệt thự ven sông, không gian xanh, thiết kế hiện đại.",
      floor: 2,
      bedroom: 5,
      bathroom: 5,
      isFurniture: true,
      direction: "Nam",
      expiredDate: "2023-11-15T23:59:59Z",
      priority: 2,
      status: "draft",
      created_at: "2023-09-05T15:45:00Z",
      updated_at: "2023-10-08T12:30:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 12,
      user_id: 3,
      title: "Căn hộ The Ascent",
      slug: "can-ho-the-ascent",
      address: "58 Quốc Hương, Thảo Điền, Quận 2, TP. Hồ Chí Minh",
      price: 5500000000,
      square_meters: 80,
      description: "Căn hộ thiết kế hiện đại, view sông Sài Gòn, nội thất cao cấp.",
      floor: 20,
      bedroom: 2,
      bathroom: 2,
      isFurniture: true,
      direction: "Tây",
      expiredDate: "2023-11-10T23:59:59Z",
      priority: 1,
      status: "expired",
      created_at: "2023-09-03T11:25:00Z",
      updated_at: "2023-10-07T14:50:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 13,
      user_id: 1,
      title: "Nhà phố Mega Ruby",
      slug: "nha-pho-mega-ruby",
      address: "12 Trường Lưu, Quận 9, TP. Hồ Chí Minh",
      price: 9800000000,
      square_meters: 150,
      description: "Nhà phố liền kề, thiết kế hiện đại, khu dân cư an ninh.",
      floor: 3,
      bedroom: 4,
      bathroom: 3,
      isFurniture: false,
      direction: "Đông Nam",
      expiredDate: "2023-11-05T23:59:59Z",
      priority: 0,
      status: "draft",
      created_at: "2023-09-01T09:15:00Z",
      updated_at: "2023-10-06T10:40:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 14,
      user_id: 2,
      title: "Căn hộ Gateway Thảo Điền",
      slug: "can-ho-gateway-thao-dien",
      address: "89 Xa lộ Hà Nội, Thảo Điền, Quận 2, TP. Hồ Chí Minh",
      price: 6200000000,
      square_meters: 90,
      description: "Căn hộ 2 phòng ngủ, nội thất cao cấp, gần trạm Metro.",
      floor: 15,
      bedroom: 2,
      bathroom: 2,
      isFurniture: true,
      direction: "Bắc",
      expiredDate: "2023-10-31T23:59:59Z",
      priority: 1,
      status: "draft",
      created_at: "2023-08-28T14:30:00Z",
      updated_at: "2023-10-05T15:20:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 15,
      user_id: 3,
      title: "Biệt thự Lucasta",
      slug: "biet-thu-lucasta",
      address: "67 Liên Phường, Quận 9, TP. Hồ Chí Minh",
      price: 22000000000,
      square_meters: 300,
      description: "Biệt thự đơn lập, sân vườn rộng, thiết kế hiện đại.",
      floor: 2,
      bedroom: 4,
      bathroom: 4,
      isFurniture: false,
      direction: "Tây Bắc",
      expiredDate: "2023-10-25T23:59:59Z",
      priority: 2,
      status: "draft",
      created_at: "2023-08-25T10:45:00Z",
      updated_at: "2023-10-04T11:35:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 16,
      user_id: 1,
      title: "Căn hộ Feliz En Vista",
      slug: "can-ho-feliz-en-vista",
      address: "2 Đường D1, Thạnh Mỹ Lợi, Quận 2, TP. Hồ Chí Minh",
      price: 7800000000,
      square_meters: 105,
      description: "Căn hộ duplex, thiết kế độc đáo, tiện ích cao cấp.",
      floor: 25,
      bedroom: 3,
      bathroom: 2,
      isFurniture: true,
      direction: "Đông",
      expiredDate: "2023-10-20T23:59:59Z",
      priority: 1,
      status: "draft",
      created_at: "2023-08-22T13:20:00Z",
      updated_at: "2023-10-03T16:15:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 17,
      user_id: 2,
      title: "Nhà phố Park Riverside",
      slug: "nha-pho-park-riverside",
      address: "43 Vũ Tông Phan, Quận 9, TP. Hồ Chí Minh",
      price: 8500000000,
      square_meters: 140,
      description: "Nhà phố ven sông, thiết kế hiện đại, khu compound an ninh.",
      floor: 3,
      bedroom: 3,
      bathroom: 3,
      isFurniture: false,
      direction: "Nam",
      expiredDate: "2023-10-15T23:59:59Z",
      priority: 0,
      status: "draft",
      created_at: "2023-08-20T09:30:00Z",
      updated_at: "2023-10-02T14:25:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 18,
      user_id: 3,
      title: "Căn hộ Empire City",
      slug: "can-ho-empire-city",
      address: "11 Mai Chí Thọ, Thủ Thiêm, Quận 2, TP. Hồ Chí Minh",
      price: 12500000000,
      square_meters: 150,
      description: "Căn hộ cao cấp, view sông và thành phố, nội thất sang trọng.",
      floor: 30,
      bedroom: 3,
      bathroom: 3,
      isFurniture: true,
      direction: "Tây Nam",
      expiredDate: "2023-10-10T23:59:59Z",
      priority: 3,
      status: "draft",
      created_at: "2023-08-18T15:40:00Z",
      updated_at: "2023-10-01T10:50:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 19,
      user_id: 1,
      title: "Biệt thự Khang Điền",
      slug: "biet-thu-khang-dien",
      address: "78 Dương Đình Hội, Quận 9, TP. Hồ Chí Minh",
      price: 18000000000,
      square_meters: 250,
      description: "Biệt thự song lập, thiết kế hiện đại, khu compound an ninh.",
      floor: 2,
      bedroom: 4,
      bathroom: 3,
      isFurniture: false,
      direction: "Đông Bắc",
      expiredDate: "2023-10-05T23:59:59Z",
      priority: 2,
      status: "draft",
      created_at: "2023-08-15T11:15:00Z",
      updated_at: "2023-09-30T13:40:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
    {
      draft_id: 20,
      user_id: 2,
      title: "Căn hộ Saigon Pearl",
      slug: "can-ho-saigon-pearl",
      address: "92 Nguyễn Hữu Cảnh, Bình Thạnh, TP. Hồ Chí Minh",
      price: 9500000000,
      square_meters: 135,
      description: "Căn hộ 3 phòng ngủ, view sông, nội thất cao cấp.",
      floor: 20,
      bedroom: 3,
      bathroom: 2,
      isFurniture: true,
      direction: "Đông Nam",
      expiredDate: "2023-10-01T23:59:59Z",
      priority: 1,
      status: "draft",
      created_at: "2023-08-12T14:25:00Z",
      updated_at: "2023-09-29T15:30:00Z",
      image: "/placeholder.svg?height=192&width=384",
    },
  ]
  
  // Helper function to get user by ID
  export const getUserById = (userId: number): User => {
    const user = mockUsers.find((u) => u.user_id === userId)
    return user || { user_id: 0, name: "Unknown User" }
  }
  
  // Helper function to format price
  export const formatPrice = (price: number): string => {
    return new Intl.NumberFormat("vi-VN", {
      style: "currency",
      currency: "VND",
      maximumFractionDigits: 0,
    }).format(price)
  }
  
  // Helper function to get status badge color
  export const getStatusColor = (status: PostDraftStatus): string => {
    switch (status) {
      case "draft":
        return "bg-gray-200 text-gray-800"
      case "pending":
        return "bg-yellow-100 text-yellow-800"
      case "published":
        return "bg-green-100 text-green-800"
      case "rejected":
        return "bg-red-100 text-red-800"
      case "expired":
        return "bg-purple-100 text-purple-800"
      default:
        return "bg-gray-200 text-gray-800"
    }
  }