
export const customers = [
  {
    id: 'KH001',
    name: 'Nguyễn Văn An',
    email: 'nguyenvanan@example.com',
    phone: '0912 345 678',
    status: 'potential',
    lastContact: '15/07/2023',
    interests: ['Căn hộ', 'Nhà phố'],
    rating: 4,
  },
  {
    id: 'KH002',
    name: 'Trần Thị Bình',
    email: 'tranthib@example.com',
    phone: '0987 654 321',
    status: 'active',
    lastContact: '20/07/2023',
    interests: ['Thương mại', 'Đất nền'],
    rating: 5,
  },
  {
    id: 'KH003',
    name: 'Lê Minh Cường',
    email: 'leminhc@example.com',
    phone: '0909 456 789',
    status: 'purchased',
    lastContact: '30/06/2023',
    interests: ['Nhà phố'],
    rating: 5,
  },
  {
    id: 'KH004',
    name: 'Phạm Thị Dung',
    email: 'phamthid@example.com',
    phone: '0978 234 567',
    status: 'potential',
    lastContact: '10/07/2023',
    interests: ['Căn hộ'],
    rating: 3,
  },
  {
    id: 'KH005',
    name: 'Hoàng Văn Em',
    email: 'hoangvane@example.com',
    phone: '0932 876 543',
    status: 'active',
    lastContact: '18/07/2023',
    interests: ['Nhà phố', 'Đất nền'],
    rating: 4,
  },
  {
    id: 'KH006',
    name: 'Ngô Thị Phương',
    email: 'ngothip@example.com',
    phone: '0918 345 678',
    status: 'purchased',
    lastContact: '05/07/2023',
    interests: ['Thương mại'],
    rating: 5,
  },
  {
    id: 'KH007',
    name: 'Đỗ Văn Giang',
    email: 'dovang@example.com',
    phone: '0965 432 109',
    status: 'potential',
    lastContact: '12/07/2023',
    interests: ['Căn hộ', 'Đất nền'],
    rating: 3,
  },
  {
    id: 'KH008',
    name: 'Vũ Thị Hương',
    email: 'vuthih@example.com',
    phone: '0912 876 543',
    status: 'active',
    lastContact: '22/07/2023',
    interests: ['Nhà phố'],
    rating: 4,
  },
  {
    id: 'KH009',
    name: 'Đinh Văn Ích',
    email: 'dinhvani@example.com',
    phone: '0934 567 890',
    status: 'purchased',
    lastContact: '01/07/2023',
    interests: ['Thương mại', 'Căn hộ'],
    rating: 5,
  },
  {
    id: 'KH010',
    name: 'Lý Thị Kim',
    email: 'lythik@example.com',
    phone: '0978 123 456',
    status: 'potential',
    lastContact: '08/07/2023',
    interests: ['Đất nền'],
    rating: 3,
  },
  {
    id: 'KH011',
    name: 'Bùi Văn Lâm',
    email: 'buivanl@example.com',
    phone: '0923 456 789',
    status: 'active',
    lastContact: '19/07/2023',
    interests: ['Căn hộ', 'Nhà phố'],
    rating: 4,
  },
  {
    id: 'KH012',
    name: 'Phan Thị Mai',
    email: 'phanthim@example.com',
    phone: '0967 890 123',
    status: 'purchased',
    lastContact: '03/07/2023',
    interests: ['Thương mại'],
    rating: 5,
  },
  {
    id: 'KH013',
    name: 'Trương Văn Nam',
    email: 'truongvann@example.com',
    phone: '0945 678 901',
    status: 'potential',
    lastContact: '14/07/2023',
    interests: ['Nhà phố', 'Đất nền'],
    rating: 3,
  },
  {
    id: 'KH014',
    name: 'Huỳnh Thị Oanh',
    email: 'huynhthio@example.com',
    phone: '0912 345 987',
    status: 'active',
    lastContact: '21/07/2023',
    interests: ['Căn hộ'],
    rating: 4,
  },
  {
    id: 'KH015',
    name: 'Dương Văn Phúc',
    email: 'duongvanp@example.com',
    phone: '0989 012 345',
    status: 'purchased',
    lastContact: '02/07/2023',
    interests: ['Thương mại', 'Nhà phố'],
    rating: 5,
  },
  {
    id: 'KH015',
    name: 'Dương Văn Phúc',
    email: 'duongvanp@example.com',
    phone: '0989 012 345',
    status: 'purchased',
    lastContact: '02/07/2023',
    interests: ['Thương mại', 'Nhà phố'],
    rating: 5,
  },
  {
    id: 'KH015',
    name: 'Dương Văn Phúc',
    email: 'duongvanp@example.com',
    phone: '0989 012 345',
    status: 'purchased',
    lastContact: '02/07/2023',
    interests: ['Thương mại', 'Nhà phố'],
    rating: 5,
  },
  {
    id: 'KH015',
    name: 'Dương Văn Phúc',
    email: 'duongvanp@example.com',
    phone: '0989 012 345',
    status: 'purchased',
    lastContact: '02/07/2023',
    interests: ['Thương mại', 'Nhà phố'],
    rating: 5,
  },
  {
    id: 'KH015',
    name: 'Dương Văn Phúc',
    email: 'duongvanp@example.com',
    phone: '0989 012 345',
    status: 'purchased',
    lastContact: '02/07/2023',
    interests: ['Thương mại', 'Nhà phố'],
    rating: 5,
  },
  {
    id: 'KH015',
    name: 'Dương Văn Phúc',
    email: 'duongvanp@example.com',
    phone: '0989 012 345',
    status: 'purchased',
    lastContact: '02/07/2023',
    interests: ['Thương mại', 'Nhà phố'],
    rating: 5,
  },
  {
    id: 'KH015',
    name: 'Dương Văn Phúc',
    email: 'duongvanp@example.com',
    phone: '0989 012 345',
    status: 'purchased',
    lastContact: '02/07/2023',
    interests: ['Thương mại', 'Nhà phố'],
    rating: 5,
  },
  {
    id: 'KH015',
    name: 'Dương Văn Phúc',
    email: 'duongvanp@example.com',
    phone: '0989 012 345',
    status: 'purchased',
    lastContact: '02/07/2023',
    interests: ['Thương mại', 'Nhà phố'],
    rating: 5,
  },
  {
    id: 'KH015',
    name: 'Dương Văn Phúc',
    email: 'duongvanp@example.com',
    phone: '0989 012 345',
    status: 'purchased',
    lastContact: '02/07/2023',
    interests: ['Thương mại', 'Nhà phố'],
    rating: 5,
  },
  {
    id: 'KH015',
    name: 'Dương Văn Phúc',
    email: 'duongvanp@example.com',
    phone: '0989 012 345',
    status: 'purchased',
    lastContact: '02/07/2023',
    interests: ['Thương mại', 'Nhà phố'],
    rating: 5,
  },
];
