
export const agents = [
  {
    id: 1,
    name: 'Nguyễn Thị Hải',
    avatar:
      'https://nld.mediacdn.vn/291774122806476800/2024/2/17/42790915710136933434537904675597409582460442n-17081694543231268820558.jpg',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987654321',
    email: 'hai@example.com',
    areas: [
      'Quận Hoàng Mai & Thanh Xuân, Hà Nội',
      'Khu vực quanh Hồ Tây',
      'Khu đô thị mới Starlake',
      'Các dự án quanh phố Láng Hạ, Hà Nội',
    ],
  },
  {
    id: 2,
    name: 'Trần Tuấn Anh',
    avatar: 'https://th.bing.com/th/id/OIP.itQejYbHpEUZEk9w_7wEuQHaHZ?rs=1&pid=ImgDetMain',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987123456',
    email: 'tuan@example.com',
    areas: ['Khu vực chung cư Vinhomes Sky Lake', 'Khu đô thị Times City', 'Khu vực chung cư The Manor Central Park'],
  },
  {
    id: 3,
    name: 'Phạm Anh',
    avatar: 'https://anhgaimup.com/wp-content/uploads/2024/04/hinh-anh-dien-vien-phuong-anh-dao-100.webp',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987111222',
    email: 'anh@example.com',
    areas: [
      'Khu đô thị mới Ciputra, Long Biên',
      'Khu vực chung cư Royal City',
      'Khu đô thị Ecopark',
      'Khu vực phía Bắc và Đông Trung Tâm',
    ],
  },
  {
    id: 4,
    name: 'Đặng Đại Thành',
    avatar: 'https://th.bing.com/th/id/OIP.pjmLJGgw70XWTs9jhwHwwQHaLH?rs=1&pid=ImgDetMain',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987333444',
    email: 'thanh@example.com',
    areas: [
      'Khu đô thị mới Dương Nội, Hà Đông',
      'Khu vực Mỹ Đình và Từ Liêm',
      'Khu đô thị mới Tây Hồ Tây, Đông Anh',
      'Khu vực Thanh Xuân',
    ],
  },
  {
    id: 5,
    name: 'Hoàng Văn Hùng',
    avatar: 'https://thethaovanhoa.mediacdn.vn/372676912336973824/2023/9/12/phuong-anh-dao-va-dan-nguoi-tinh-man-anh-toan-trai-dep-noi-tieng-0f410351-1694518424271-16945184244201188187746.jpg',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987555666',
    email: 'hung@example.com',
    areas: [
      'Khu đô thị mới Linh Đàm, Hoàng Mai',
      'Khu vực Cầu Giấy và Dịch Vọng',
      'Khu đô thị mới Tây Hồ Tây, Đông Anh',
    ],
  },
  {
    id: 6,
    name: 'Nguyễn Thanh Sơn',
    avatar: '/placeholder.svg?height=80&width=80',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987777888',
    email: 'son@example.com',
    areas: ['Khu vực chung cư Đông Hà, Đông Anh', 'Khu đô thị Vinhomes Ocean Park', 'Khu vực chung cư Sunshine City'],
  },
  {
    id: 7,
    name: 'Trần Anh Thư',
    avatar: '/placeholder.svg?height=80&width=80',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987999000',
    email: 'thu@example.com',
    areas: [
      'Khu vực chung cư Thăng Long, Đại Mỗ',
      'Khu đô thị mới Ciputra, Long Biên',
      'Khu vực chung cư Vinhomes Smart City',
    ],
  },
  {
    id: 8,
    name: 'Phạm Thị Trang',
    avatar: '/placeholder.svg?height=80&width=80',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987111333',
    email: 'trang@example.com',
    areas: [
      'Khu vực chung cư Royal City, Thanh Xuân',
      'Khu đô thị mới Tây Hồ Tây, Đông Anh',
      'Khu vực chung cư Vinhomes Ocean Park',
    ],
  },
  {
    id: 9,
    name: 'Nguyễn Quý Sơn',
    avatar: '/placeholder.svg?height=80&width=80',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987222444',
    email: 'quyson@example.com',
    areas: [
      'Khu vực chung cư Thăng Long, Đại Mỗ',
      'Khu đô thị mới Ciputra, Long Biên',
      'Khu vực chung cư Vinhomes Smart City',
    ],
  },
  {
    id: 10,
    name: 'Châu Văn',
    avatar: '/placeholder.svg?height=80&width=80',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987333555',
    email: 'chau@example.com',
    areas: [
      'Khu vực chung cư Thăng Long, Đại Mỗ',
      'Khu đô thị mới Ciputra, Long Biên',
      'Khu vực chung cư Vinhomes Smart City',
    ],
  },
  {
    id: 11,
    name: 'Hoàng Thị Diễm',
    avatar: '/placeholder.svg?height=80&width=80',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987444666',
    email: 'diem@example.com',
    areas: [
      'Khu vực chung cư Thăng Long, Đại Mỗ',
      'Khu đô thị mới Ciputra, Long Biên',
      'Khu vực chung cư Vinhomes Smart City',
    ],
  },
  {
    id: 12,
    name: 'Trịnh Lê',
    avatar: '/placeholder.svg?height=80&width=80',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987555777',
    email: 'le@example.com',
    areas: [
      'Khu vực chung cư Thăng Long, Đại Mỗ',
      'Khu đô thị mới Ciputra, Long Biên',
      'Khu vực chung cư Vinhomes Smart City',
    ],
  },
  {
    id: 13,
    name: 'Nguyễn Quý Kiên',
    avatar: '/placeholder.svg?height=80&width=80',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987666888',
    email: 'kien@example.com',
    areas: [
      'Khu vực chung cư Thăng Long, Đại Mỗ',
      'Khu đô thị mới Ciputra, Long Biên',
      'Khu vực chung cư Vinhomes Smart City',
    ],
  },
  {
    id: 14,
    name: 'Phạm Thu Trang',
    avatar: '/placeholder.svg?height=80&width=80',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987777999',
    email: 'thutrang@example.com',
    areas: [
      'Khu vực chung cư Thăng Long, Đại Mỗ',
      'Khu đô thị mới Ciputra, Long Biên',
      'Khu vực chung cư Vinhomes Smart City',
    ],
  },
  {
    id: 15,
    name: 'Hoàng Thị Diễm Anh',
    avatar: '/placeholder.svg?height=80&width=80',
    position: 'Chuyên viên tư vấn, Phòng Kinh Doanh',
    phone: '0987888000',
    email: 'diemanh@example.com',
    areas: [
      'Khu vực chung cư Thăng Long, Đại Mỗ',
      'Khu đô thị mới Ciputra, Long Biên',
      'Khu vực chung cư Vinhomes Smart City',
    ],
  },
];

export const recommendedProperties: { id: string; title: string; price: string; pricePerMonth?: string; area: string; location: string; images: string[]; isFavorite: boolean; }[] = [
    {
      id: '1',
      title: 'Chung cư cao cấp Gemory Định giá 4,5 tỷ rẻ nhất thị trường khi mua',
      price: '4.5 tỷ',
      area: '62 m²',
      location: 'Nam Từ Liêm, Hà Nội',
      images: [
        'https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg',
        '/images/property1-2.jpg',
        '/images/property1-3.jpg',
      ],
      isFavorite: false,
    },
    {
      id: '2',
      title: 'Cho thuê căn hộ studio - 1 PN - 2 PN tại Ecolife Capitol với giá r',
      price: '11 triệu/tháng',
      area: '75 m²',
      location: 'Nam Từ Liêm, Hà Nội',
      images: [
        'https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg',
        '/images/property2-2.jpg',
      ],
      pricePerMonth: '11 triệu',
      isFavorite: true,
    },
    {
      id: '3',
      title: 'Bán nhà 4 tầng phân lô vip trạch, ngõ thông kinh doanh phố',
      price: '39 tỷ',
      area: '115 m²',
      location: 'Đống Đa, Hà Nội',
      images: [
        'https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg',
        '/images/property3-2.jpg',
        '/images/property3-3.jpg',
      ],
      isFavorite: false,
    },
    {
      id: '4',
      title: 'Nhà 7 tỷ có nhà đẹp TDL ĐT45m2 57 ngõ thông rộng',
      price: 'Giá thỏa thuận',
      area: '45 m²',
      location: 'Đống Đa, Hà Nội',
      images: ['https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg'],
      isFavorite: false,
    },
    {
      id: '5',
      title: 'Biệt thự ven hồ Tây - View đẹp - Nội thất sang trọng',
      price: '75 tỷ',
      area: '250 m²',
      location: 'Tây Hồ, Hà Nội',
      images: [
        'https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg',
        '/images/property5-2.jpg',
      ],
      isFavorite: true,
    },
    {
      id: '6',
      title: 'Căn hộ cao cấp Vinhomes Ocean Park 3PN giá tốt nhất',
      price: '6.8 tỷ',
      area: '90 m²',
      location: 'Gia Lâm, Hà Nội',
      images: [
        'https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg',
        '/images/property6-2.jpg',
        '/images/property6-3.jpg',
      ],
      isFavorite: false,
    },
    {
      id: '7',
      title: 'Bán nhà riêng tại Cầu Giấy - Nhà đẹp, ngõ ô tô vào tận cửa',
      price: '9.2 tỷ',
      area: '80 m²',
      location: 'Cầu Giấy, Hà Nội',
      images: ['https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg'],
      isFavorite: true,
    },
    {
      id: '8',
      title: 'Nhà mặt phố Trung Hòa - Kinh doanh sầm uất - Giá cực tốt',
      price: '56 tỷ',
      area: '120 m²',
      location: 'Cầu Giấy, Hà Nội',
      images: [
        'https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg',
        '/images/property8-2.jpg',
      ],
      isFavorite: false,
    },
    {
      id: '9',
      title: 'Shophouse The Manor Central Park - Vị trí đắc địa',
      price: '21 tỷ',
      area: '100 m²',
      location: 'Hoàng Mai, Hà Nội',
      images: [
        'https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg',
        '/images/property9-2.jpg',
      ],
      isFavorite: false,
    },
    {
      id: '10',
      title: 'Căn hộ studio tại Times City - Giá hấp dẫn',
      price: '3.5 tỷ',
      area: '50 m²',
      location: 'Hai Bà Trưng, Hà Nội',
      images: ['https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg'],
      isFavorite: true,
    },
    {
      id: '11',
      title: 'Nhà phố thương mại tại KĐT Ciputra - Tiện ích đầy đủ',
      price: '28 tỷ',
      area: '150 m²',
      location: 'Tây Hồ, Hà Nội',
      images: [
        'https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg',
        '/images/property11-2.jpg',
      ],
      isFavorite: false,
    },
    {
      id: '12',
      title: 'Bán biệt thự liền kề 4 tầng tại Vinhomes Smart City',
      price: '15 tỷ',
      area: '200 m²',
      location: 'Nam Từ Liêm, Hà Nội',
      images: [
        'https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg',
        '/images/property12-2.jpg',
      ],
      isFavorite: true,
    },
    {
      id: '13',
      title: 'Căn hộ 2PN tại Sunshine City - Nội thất hiện đại',
      price: '5.2 tỷ',
      area: '75 m²',
      location: 'Bắc Từ Liêm, Hà Nội',
      images: ['https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg'],
      isFavorite: false,
    },
    {
      id: '14',
      title: 'Nhà riêng tại Long Biên - Gần cầu Chương Dương',
      price: '6.5 tỷ',
      area: '85 m²',
      location: 'Long Biên, Hà Nội',
      images: [
        'https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg',
        '/images/property14-2.jpg',
      ],
      isFavorite: false,
    },
    {
      id: '15',
      title: 'Bán đất nền dự án VinCity Ocean Park - Đầu tư sinh lời',
      price: '12 tỷ',
      area: '300 m²',
      location: 'Gia Lâm, Hà Nội',
      images: ['https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg'],
      isFavorite: true,
    },
    {
      id: '16',
      title: 'Bán nhà mặt phố cổ Hàng Ngang - Khu kinh doanh sầm uất',
      price: '100 tỷ',
      area: '180 m²',
      location: 'Hoàn Kiếm, Hà Nội',
      images: [
        'https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg',
        '/images/property16-2.jpg',
      ],
      isFavorite: false,
    },
  ];
