export const realEstateListings = [
    {
      id: 1,
      location: "Quận 1, TP. Hồ Chí Minh",
      images: [
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
      ],
      title: "Nhà phố 3 tầng gần trung tâm quận 1",
      area: "120m²",
      description: "Nhà phố thiết kế hiện đại, gần trung tâm, thuận tiện di chuyển.",
      details: {
        price: "12 tỷ",
        bedrooms: 4,
        bathrooms: 3,
        floors: 3,
        direction: "Đông Nam",
        balconyDirection: "Tây Bắc",
        frontage: "5m",
        alleyWidth: "8m",
        legal: "Sổ hồng chính chủ",
        furniture: "Full nội thất cao cấp",
      },
      googleMap: "https://maps.google.com/?q=10.7769,106.7009",
      poster: {
        name: "Nguyễn Văn A",
        phone: "0912345678",
        email: "nguyenvana@example.com",
        image: "https://th.bing.com/th/id/OIP.5z3tSnN6TDMrwyp7C_55_QHaHa?rs=1&pid=ImgDetMain",
      },
    },
    {
      id: 2,
      location: "Quận 7, TP. Hồ Chí Minh",
      images: [
        "https://th.bing.com/th?id=OIP.cz2Q-TonAb--ymkDBmOwygHaFG&w=301&h=207&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
        "https://th.bing.com/th?id=OIP.cz2Q-TonAb--ymkDBmOwygHaFG&w=301&h=207&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
        "https://th.bing.com/th?id=OIP.cz2Q-TonAb--ymkDBmOwygHaFG&w=301&h=207&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
        "https://th.bing.com/th?id=OIP.cz2Q-TonAb--ymkDBmOwygHaFG&w=301&h=207&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
        "https://th.bing.com/th?id=OIP.cz2Q-TonAb--ymkDBmOwygHaFG&w=301&h=207&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
        "https://th.bing.com/th?id=OIP.cz2Q-TonAb--ymkDBmOwygHaFG&w=301&h=207&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
      ],
      title: "Căn hộ cao cấp Quận 7, view sông",
      area: "80m²",
      description: "Căn hộ 2PN, nội thất đầy đủ, tiện ích 5 sao.",
      details: {
        price: "4.5 tỷ",
        bedrooms: 2,
        bathrooms: 2,
        floors: 20,
        direction: "Tây Nam",
        balconyDirection: "Đông Bắc",
        frontage: "Không áp dụng",
        alleyWidth: "Không áp dụng",
        legal: "Sổ hồng",
        furniture: "Full nội thất",
      },
      googleMap: "https://maps.google.com/?q=10.7320,106.7218",
      poster: {
        name: "Trần Thị B",
        phone: "0987654321",
        email: "tranthib@example.com",
        image: "https://th.bing.com/th/id/OIP.5z3tSnN6TDMrwyp7C_55_QHaHa?rs=1&pid=ImgDetMain",
      },
    },
    {
      id: 3,
      location: "Quận 2, TP. Hồ Chí Minh",
      images: [
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
      ],
      title: "Biệt thự sân vườn Quận 2, khu an ninh",
      area: "250m²",
      description: "Biệt thự rộng rãi, sân vườn thoáng mát, có hồ bơi riêng.",
      details: {
        price: "35 tỷ",
        bedrooms: 5,
        bathrooms: 6,
        floors: 2,
        direction: "Nam",
        balconyDirection: "Đông",
        frontage: "10m",
        alleyWidth: "10m",
        legal: "Sổ đỏ chính chủ",
        furniture: "Nội thất cao cấp",
      },
      googleMap: "https://maps.google.com/?q=10.7891,106.7401",
      poster: {
        name: "Lê Minh C",
        phone: "0975123456",
        email: "leminhc@example.com",
        image: "https://th.bing.com/th/id/OIP.5z3tSnN6TDMrwyp7C_55_QHaHa?rs=1&pid=ImgDetMain",
      },
    },
    {
      id: 4,
      location: "Quận 5, TP. Hồ Chí Minh",
      images: [
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
      ],
      title: "Nhà mặt tiền Quận 5, tiện kinh doanh",
      area: "100m²",
      description: "Nhà mặt tiền đường lớn, tiện mở cửa hàng, văn phòng.",
      details: {
        price: "20 tỷ",
        bedrooms: 3,
        bathrooms: 3,
        floors: 4,
        direction: "Bắc",
        balconyDirection: "Nam",
        frontage: "6m",
        alleyWidth: "Không áp dụng",
        legal: "Sổ hồng",
        furniture: "Không nội thất",
      },
      googleMap: "https://maps.google.com/?q=10.7591,106.6705",
      poster: {
        name: "Đặng Hoàng D",
        phone: "0902345678",
        email: "danghoangd@example.com",
        image: "https://th.bing.com/th/id/OIP.5z3tSnN6TDMrwyp7C_55_QHaHa?rs=1&pid=ImgDetMain",
      },
    },
    {
      id: 5,
      location: "Quận 10, TP. Hồ Chí Minh",
      images: [
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
      ],
      title: "Căn hộ chung cư trung tâm Quận 10",
      area: "70m²",
      description: "Căn hộ tầng cao, thoáng mát, đầy đủ tiện ích.",
      details: {
        price: "3.2 tỷ",
        bedrooms: 2,
        bathrooms: 2,
        floors: 15,
        direction: "Đông Bắc",
        balconyDirection: "Tây Nam",
        frontage: "Không áp dụng",
        alleyWidth: "Không áp dụng",
        legal: "Sổ hồng",
        furniture: "Nội thất cơ bản",
      },
      googleMap: "https://maps.google.com/?q=10.7765,106.6823",
      poster: {
        name: "Phạm Thu E",
        phone: "0913456789",
        email: "phamthue@example.com",
        image: "https://th.bing.com/th/id/OIP.5z3tSnN6TDMrwyp7C_55_QHaHa?rs=1&pid=ImgDetMain",
      },
    },
    {
      id: 6,
      location: "Quận 9, TP. Hồ Chí Minh",
      images: [
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
        "https://hoanghamobile.com/tin-tuc/wp-content/uploads/2024/04/anh-ha-noi.jpg",
      ],
      title: "Biệt thự liền kề Quận 9, khu VIP",
      area: "200m²",
      description: "Biệt thự cao cấp, khu dân cư an ninh, gần trung tâm.",
      details: {
        price: "25 tỷ",
        bedrooms: 4,
        bathrooms: 5,
        floors: 3,
        direction: "Tây",
        balconyDirection: "Đông",
        frontage: "8m",
        alleyWidth: "Không áp dụng",
        legal: "Sổ hồng",
        furniture: "Full nội thất nhập khẩu",
      },
      googleMap: "https://maps.google.com/?q=10.8305,106.7812",
      poster: {
        name: "Ngô Thanh F",
        phone: "0935678901",
        email: "ngothanhf@example.com",
        image: "https://th.bing.com/th/id/OIP.5z3tSnN6TDMrwyp7C_55_QHaHa?rs=1&pid=ImgDetMain",
      },
    },
  ]
  
  export const cityInfos = [
    {
      name: "TP. Hồ Chí Minh",
      count: 63542,
      image: "https://file4.batdongsan.com.vn/images/newhome/cities/HCM-web-1.jpg",
    },
    {
      name: "Hà Nội",
      count: 10000,
      image: "https://file4.batdongsan.com.vn/images/newhome/cities/HN-web-1.jpg",
    },
    {
      name: "Đà Nẵng",
      count: 9813,
      image: "https://file4.batdongsan.com.vn/images/newhome/cities/DN-web-1.jpg",
    },
    {
      name: "Bình Dương",
      count: 8071,
      image: "https://file4.batdongsan.com.vn/images/newhome/cities/BD-web-1.jpg",
    },
    {
      name: "Đồng Nai",
      count: 4322,
      image: "https://file4.batdongsan.com.vn/images/newhome/cities/DN2-web-1.jpg",
    },
  ]
  
  export const allCities = [
    "An Giang",
    "Bà Rịa Vũng Tàu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bạc Liêu",
    "Bắc Ninh",
    "Bến Tre",
    "Bình Định",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Cà Mau",
    "Cần Thơ",
    "Cao Bằng",
    "Đà Nẵng",
    "Đắk Lắk",
    "Đắk Nông",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Nội",
    "Hà Tĩnh",
    "Hải Dương",
    "Hải Phòng",
    "Hậu Giang",
    "Hòa Bình",
    "Hưng Yên",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Lâm Đồng",
    "Lạng Sơn",
    "Lào Cai",
    "Long An",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Phú Yên",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên Huế",
    "Tiền Giang",
    "TP Hồ Chí Minh",
    "Trà Vinh",
    "Tuyên Quang",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái",
  ]
  
  export const featuredCities = [
    {
      name: "Hà Nội",
      image: "/images/hanoi.jpg",
    },
    {
      name: "Hồ Chí Minh",
      image: "/images/hochiminh.jpg",
    },
    {
      name: "Đà Nẵng",
      image: "/images/danang.jpg",
    },
    {
      name: "Bình Dương",
      image: "/images/binhduong.jpg",
    },
    {
      name: "Đồng Nai",
      image: "/images/dongnai.jpg",
    },
    {
      name: "Khánh Hòa",
      image: "/images/khanhhoa.jpg",
    },
  ]
  
  export  const customScrollbarStyles = `
  .custom-scrollbar::-webkit-scrollbar {
    width: 6px;
  }
  .custom-scrollbar::-webkit-scrollbar-track {
    background: #f1f1f1;
    border-radius: 10px;
  }
  .custom-scrollbar::-webkit-scrollbar-thumb {
    background: #d1d1d1;
    border-radius: 10px;
  }
  .custom-scrollbar::-webkit-scrollbar-thumb:hover {
    background: #c1c1c1;
  }
`

// Vietnam provinces and districts data
export const vietnamProvinces = [
  {
    name: "Hà Nội",
    districts: [
      "Quận Ba Đình",
      "Quận Bắc Từ Liêm",
      "Quận Cầu Giấy",
      "Quận Đống Đa",
      "Quận Hà Đông",
      "Quận Hai Bà Trưng",
      "Quận Hoàn Kiếm",
      "Quận Hoàng Mai",
      "Quận Long Biên",
      "Quận Nam Từ Liêm",
      "Quận Tây Hồ",
      "Quận Thanh Xuân",
      "Huyện Ba Vì",
      "Huyện Chương Mỹ",
      "Huyện Đan Phượng",
      "Huyện Đông Anh",
      "Huyện Gia Lâm",
      "Huyện Hoài Đức",
      "Huyện Mê Linh",
      "Huyện Mỹ Đức",
      "Huyện Phú Xuyên",
      "Huyện Phúc Thọ",
      "Huyện Quốc Oai",
      "Huyện Sóc Sơn",
      "Huyện Thạch Thất",
      "Huyện Thanh Oai",
      "Huyện Thanh Trì",
      "Huyện Thường Tín",
      "Huyện Ứng Hòa",
      "Thị xã Sơn Tây",
    ],
  },
  {
    name: "Hồ Chí Minh",
    districts: [
      "Quận 1",
      "Quận 3",
      "Quận 4",
      "Quận 5",
      "Quận 6",
      "Quận 7",
      "Quận 8",
      "Quận 10",
      "Quận 11",
      "Quận 12",
      "Quận Bình Tân",
      "Quận Bình Thạnh",
      "Quận Gò Vấp",
      "Quận Phú Nhuận",
      "Quận Tân Bình",
      "Quận Tân Phú",
      "Quận Thủ Đức",
      "Huyện Bình Chánh",
      "Huyện Cần Giờ",
      "Huyện Củ Chi",
      "Huyện Hóc Môn",
      "Huyện Nhà Bè",
    ],
  },
  {
    name: "Đà Nẵng",
    districts: [
      "Quận Hải Châu",
      "Quận Cẩm Lệ",
      "Quận Thanh Khê",
      "Quận Liên Chiểu",
      "Quận Ngũ Hành Sơn",
      "Quận Sơn Trà",
      "Huyện Hòa Vang",
      "Huyện Hoàng Sa",
    ],
  },
  // Adding a few more provinces for demonstration
  {
    name: "Hải Phòng",
    districts: [
      "Quận Hồng Bàng",
      "Quận Lê Chân",
      "Quận Ngô Quyền",
      "Quận Kiến An",
      "Quận Hải An",
      "Quận Đồ Sơn",
      "Quận Dương Kinh",
      "Huyện An Dương",
      "Huyện An Lão",
      "Huyện Kiến Thụy",
      "Huyện Tiên Lãng",
      "Huyện Vĩnh Bảo",
      "Huyện Cát Hải",
      "Huyện Thủy Nguyên",
      "Huyện Bạch Long Vĩ",
    ],
  },
  {
    name: "Cần Thơ",
    districts: [
      "Quận Ninh Kiều",
      "Quận Bình Thủy",
      "Quận Cái Răng",
      "Quận Ô Môn",
      "Quận Thốt Nốt",
      "Huyện Vĩnh Thạnh",
      "Huyện Cờ Đỏ",
      "Huyện Phong Điền",
      "Huyện Thới Lai",
    ],
  },
  // In a real application, you would include all 63 provinces
]

// Add the remaining provinces with empty district arrays
export const vietnameseProvinces = [
  "Hà Nội",
  "Hồ Chí Minh",
  "Đà Nẵng",
  "Hải Phòng",
  "Cần Thơ",
  "An Giang",
  "Bà Rịa - Vũng Tàu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bạc Liêu",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Định",
  "Bình Dương",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cao Bằng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Tĩnh",
  "Hải Dương",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái",
]